### ISSUE TITLE
Hyprland Compatibility

### ISSUE THREAD

**Issue by ElectricalFault** [ikz87/GLWall#4]
I've been trying to make this work with Hyprland, but Hyprwinwrap (the fork of xwinwrap for Hyprland) expects a class for it. I've tried GLWall, but that doesn't seem to do anything.
```
Window 1e665d30 -> GLWall ~/Downloads/shader.glsl:
class: kitty
title: GLWall ~/Downloads/shader.glsl
initialClass: kitty
initialTitle: kitty

Window 1e65f210 -> GLWall:
class: 
title: GLWall
initialClass: 
initialTitle: GLWall
```
As you may see above, there's no class for it. Do you happen to know a solution?

**Comment by ikz87** [comment]
Did [12f7f27](https://github.com/ikz87/GLWall/commit/12f7f27342f6526577cc8f0937f5c069fbe6e122) fix this? I merged the commit either way but need confirmation before closing the issue :)
